# Generated by Django 4.2.7 on 2024-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo/'),
        ),
    ]
