version: '3'
services:
  redis:
    image:  redis
    ports:
      - '6379:6379'
  celery:
    build:  .
    tty:  true
    command:  celery -A online_learning worker -l INFO
    depends_on:
      - redis
      - app
  celery_beat:
    build: .
    tty: true
    command: celery -A online_learning worker -l INFO
    depends_on:
      - redis
      - app
  app:
    tty:  true
    build:  .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition:  service_healthy
  db:
    image:  postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test:  ["CMD-SHELL", "pg_isready"]
      interval:  10s
      timeout:  5s
volumes:
  pg_data: